FROM python:3.8

WORKDIR /app

RUN pip install --upgrade pip

COPY . .
RUN pip install -e catanatron_core
RUN pip install -e catanatron_server
RUN pip install -e catanatron_gym
RUN pip install -e catanatron_experimental

EXPOSE 5000

ENV FLASK_DEBUG=1
ENV FLASK_APP=catanatron_server/catanatron_server
ENV FLASK_RUN_HOST=0.0.0.0

CMD flask run
