const ACTIONS = Object.freeze({
  SET_LEFT_DRAWER_OPENED: "SET_LEFT_DRAWER_OPENED",
  SET_GAME_STATE: "SET_GAME_STATE",

  SET_IS_BUILDING_ROAD: "SET_IS_BUILDING_ROAD",
  SET_IS_BUILDING_SETTLEMENT: "SET_IS_BUILDING_SETTLEMENT",
  SET_IS_BUILDING_CITY: "SET_IS_BUILDING_CITY",
  SET_IS_PLAYING_YEAR_OF_PLENTY: "SET_IS_PLAYING_YEAR_OF_PLENTY",
  PLAY_YEAR_OF_PLENTY: "PLAY_YEAR_OF_PLENTY",
  PLAY_ROAD_BUILDING: "PLAY_ROAD_BUILDING",
  PLAY_KNIGHT_CARD: "PLAY_KNIGHT_CARD",
  SET_IS_MOVING_ROBBER: "SET_IS_MOVING_ROBBER",
});

export default ACTIONS;
