"""
THIS FILE SERVES AS THE ABOVE ALL CONFIGURATION FILE FOR THE AGENT

MANY OF THE MODELS AND ENVIRONMENTAL FEATURES RELY ON SPECIFIC CONSTANTS
SUCH AS THE OBSERVATION SIZE, ACTION SIZE, AND OTHER VARIABLES

TO MAKE IT EASIER TO UPDATE THESE VALUES IN CODE (SUCH AS MODIFYING THE OBSERVATION SPACE)
THIS CONSTANTS FILE COMPILES ALL OF THE KEY VARIABLES TOGETHER, MAKING LARGE
MODIFICATIONS EASIER AND LESS BUG PRONE

"""

# MODELS
PLACEMENT_AGENT_HIDDEN_SIZE = 256
MAIN_PLAY_AGENT_HIDDEN_SIZE = 512

FEATURE_SPACE_SIZE = 1259
ACTION_SPACE_SIZE = 245

# FEATURE SPACE LAYOUT
HEX_FEATURE_SLICE = slice(0, 114) # 19 hexes * 6 nodes
VERTEX_FEATURE_SLICE = slice(114, 870) # 54 vertices * 14 features
EDGE_FEATURE_SLICE = slice(870, 1158) # 72 edges * 4 features
HAND_FEATURE_SLICE = slice(1158, 1185) # 16 Self, 11 Opp
STRATEGIC_FEATURE_SLICE = slice(1185, 1229) # 44 strategic features
GAME_FEATURE_SLICE = slice(1229, 1259)
IS_SETTLEMENT_PHASE_FEATURE_INDEX = 1230
IS_PLAYER_2_FEATURE_INDEX = 1231


# ACTION SPACE LAYOUT
ROAD_ACTION_SLICE       = slice(0, 72)      # 72 edges
SETTLEMENT_ACTION_SLICE = slice(72, 126)    # 54 nodes
CITY_ACTION_SLICE       = slice(126, 180)   # 54 nodes
ROBBER_ACTION_SLICE     = slice(180, 199)   # 19 land tiles
DISCARD_ACTION_IDX      = 199
MARITIME_ACTION_SLICE   = slice(200, 220)   # 20 give/take pairs
BUY_DEV_ACTION_IDX      = 220
KNIGHT_ACTION_IDX       = 221
ROAD_BUILDER_ACTION_IDX   = 222
YOP_ACTION_SLICE        = slice(223, 238)   # 15 resource-pair combos
MONOPOLY_ACTION_SLICE   = slice(238, 243)   # 5 resources
END_TURN_ACTION_IDX     = 243
ROLL_ACTION_IDX         = 244

# GAMEPLAY
MAX_STEPS_PER_GAME = 1000

DEV_CARD_COUNTS = [14, 2, 2, 2, 5] # KNIGHT,YEAR_OF_PLENTY, MONOPOLY, ROAD_BUILDING, VICTORY_POINT
TOTAL_KNIGHT_COUNTS = DEV_CARD_COUNTS[0]
NUM_DEV_CARDS = sum(DEV_CARD_COUNTS)
NUM_STARTING_ROADS = 15 # from PLAYER_INITIAL_STATE
CLAIM_ARMY_SIZE = 3
CLAIM_ROAD_LENGTH = 5
NUM_RESOURCES = 5
NUM_RESOURCE_PAIRS = 15
ROBBER_ACTION_SIZE = ROBBER_ACTION_SLICE.stop - ROBBER_ACTION_SLICE.start
VERTEX_ACTION_SIZE = SETTLEMENT_ACTION_SLICE.stop - SETTLEMENT_ACTION_SLICE.start
EDGE_ACTION_SIZE = ROAD_ACTION_SLICE.stop - ROAD_ACTION_SLICE.start
TRADING_ACTION_SIZE = MARITIME_ACTION_SLICE.stop - MARITIME_ACTION_SLICE.start
PLAY_DEV_ACTION_SIZE = 3 # Buy Dev, Play Knight, Play Road Building (the others have their own section in the models)
TURN_MANAGEMENT_ACTION_SIZE = 3 # Discard, End Turn, Roll (see action_map.py)
VALUE_SIZE = 1 # Value head is always size 1


# LOAD/STORE DEFAULTS
DEFAULT_MAIN_PLAY_MODEL_PATH = "capstone_agent/models/capstone_model.pt"
DEFAULT_PLACEMENT_MODEL_PATH = "capstone_agent/models/placement_model.pt"
DEFAULT_BENCHMARK_CSV = "capstone_agent/benchmarks/training_metrics.csv"
