#!/usr/bin/env python3
"""Export deterministic Python board geometry for the Rust core.

The output deliberately preserves Python node IDs and cube coordinates while
giving Rust a sorted, undirected edge catalogue.  Run with ``--check`` to
verify committed generated artifacts without overwriting them.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from catanatron.models.map import BASE_MAP_TEMPLATE, MINI_MAP_TEMPLATE, CatanMap
from catanatron.models.tiles import LandTile, Port


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests" / "fixtures" / "topology"
GENERATED = ROOT / "crates" / "core" / "src" / "generated"


def canonical(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def topology(name: str, template: Any) -> dict[str, Any]:
    game_map = CatanMap.from_template(template)
    land = sorted(game_map.land_tiles.items())
    land_nodes = sorted(game_map.land_nodes)
    edges = sorted({tuple(sorted(edge)) for tile in game_map.tiles.values() for edge in tile.edges.values() if edge[0] in game_map.land_nodes and edge[1] in game_map.land_nodes})
    tile_rows = [
        {
            "coordinate": list(coordinate),
            "id": tile.id,
            "nodes": [tile.nodes[ref] for ref in tile.nodes],
        }
        for coordinate, tile in land
    ]
    ports = [
        {
            "coordinate": list(coordinate),
            "id": tile.id,
            "nodes": sorted(tile.nodes.values()),
        }
        for coordinate, tile in sorted(game_map.tiles.items())
        if isinstance(tile, Port)
    ]
    adjacency = {str(node): sorted(neighbors) for node, neighbors in sorted((node, set()) for node in land_nodes)}
    for a, b in edges:
        adjacency[str(a)].append(b)
        adjacency[str(b)].append(a)
    for neighbors in adjacency.values():
        neighbors.sort()
    result = {
        "fixture_version": 1,
        "map": name,
        "land_nodes": land_nodes,
        "edges": [list(edge) for edge in edges],
        "land_tiles": tile_rows,
        "ports": ports,
        "adjacency": adjacency,
    }
    validate(result)
    return result


def validate(data: dict[str, Any]) -> None:
    nodes, edges, tiles = data["land_nodes"], data["edges"], data["land_tiles"]
    if data["map"] == "BASE" and (len(nodes), len(edges), len(tiles)) != (54, 72, 19):
        raise ValueError("BASE geometry must contain 54 nodes, 72 edges, and 19 land tiles")
    if len(edges) != len({tuple(edge) for edge in edges}):
        raise ValueError("duplicate undirected edge")
    node_set = set(nodes)
    if any(a not in node_set or b not in node_set or a >= b for a, b in map(tuple, edges)):
        raise ValueError("edge endpoints are not valid sorted land nodes")
    if any(len(neighbors) > 3 for neighbors in data["adjacency"].values()):
        raise ValueError("land node degree exceeds 3")
    if any(len(tile["nodes"]) != 6 or not set(tile["nodes"]).issubset(node_set) for tile in tiles):
        raise ValueError("land tile must have six land-node vertices")


def rust_module(data: dict[str, Any]) -> str:
    upper = data["map"].upper()
    edges = ", ".join(f"({a}, {b})" for a, b in data["edges"])
    nodes = ", ".join(map(str, data["land_nodes"]))
    tiles = ", ".join(
        "(" + ", ".join(map(str, tile["nodes"])) + ")"
        for tile in data["land_tiles"]
    )
    node_mask = sum(1 << node for node in data["land_nodes"])
    edge_mask = (1 << len(data["edges"])) - 1
    tile_mask = (1 << len(data["land_tiles"])) - 1
    source = (
        "// @generated by rust/tools/export_topology.py; do not hand-edit.\n"
        f"pub const {upper}_LAND_NODES: &[u8] = &[{nodes}];\n"
        f"pub const {upper}_EDGES: &[(u8, u8)] = &[{edges}];\n"
        f"pub const {upper}_LAND_TILE_NODES: &[(u8, u8, u8, u8, u8, u8)] = &[{tiles}];\n"
        f"pub const {upper}_ACTIVE_NODE_MASK: u64 = {node_mask};\n"
        f"pub const {upper}_ACTIVE_EDGE_MASK: u128 = {edge_mask};\n"
        f"pub const {upper}_ACTIVE_TILE_MASK: u32 = {tile_mask};\n"
    )
    formatted = subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        input=source,
        text=True,
        check=True,
        capture_output=True,
    )
    return formatted.stdout


def expected_files(directory: Path) -> dict[Path, str]:
    base = topology("BASE", BASE_MAP_TEMPLATE)
    mini = topology("MINI", MINI_MAP_TEMPLATE)
    return {
        directory / "BASE.json": canonical(base),
        directory / "MINI.json": canonical(mini),
        GENERATED / "base.rs": rust_module(base),
        GENERATED / "mini.rs": rust_module(mini),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = expected_files(OUT)
    mismatches = [path for path, contents in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != contents]
    if args.check:
        if mismatches:
            raise SystemExit("topology artifacts differ: " + ", ".join(map(str, mismatches)))
        print("topology fixtures and generated tables match")
        return
    for path, contents in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(expected[OUT / "BASE.json"].encode()).hexdigest()
    print(f"wrote topology artifacts (BASE SHA-256 {digest})")


if __name__ == "__main__":
    main()
