#!/usr/bin/env python3
"""Export the pinned Python Gym action catalogue as semantic Rust keys."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

from catanatron.gym.envs.action_space import get_action_array
from catanatron.models.board import get_edges
from catanatron.models.enums import ActionType, RESOURCES
from catanatron.models.map import build_map
from catanatron.models.player import Color


ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "crates" / "python" / "src" / "generated"
COLORS = (Color.RED, Color.BLUE, Color.ORANGE, Color.WHITE)
RESOURCE = {value: index for index, value in enumerate(RESOURCES)}


def key(action_type: ActionType, value, map_type: str, colors: tuple[Color, ...]) -> str:
    game_map = build_map(map_type)
    edges = sorted({tuple(sorted(edge)) for edge in get_edges(game_map.land_nodes)})
    tiles = {coordinate: index for index, coordinate in enumerate(sorted(game_map.land_tiles))}
    if action_type == ActionType.ROLL:
        return "ROLL"
    if action_type == ActionType.DISCARD_RESOURCE:
        return f"DISCARD:{RESOURCE[value]}"
    if action_type == ActionType.BUILD_ROAD:
        return f"ROAD:{edges.index(tuple(sorted(value)))}"
    if action_type == ActionType.BUILD_SETTLEMENT:
        return f"SETTLEMENT:{value}"
    if action_type == ActionType.BUILD_CITY:
        return f"CITY:{value}"
    if action_type == ActionType.BUY_DEVELOPMENT_CARD:
        return "BUY_DEV"
    if action_type == ActionType.PLAY_KNIGHT_CARD:
        return "KNIGHT"
    if action_type == ActionType.PLAY_YEAR_OF_PLENTY:
        cards = [RESOURCE[item] for item in value]
        return "YOP:" + ":".join(map(str, cards))
    if action_type == ActionType.PLAY_ROAD_BUILDING:
        return "ROAD_BUILDING"
    if action_type == ActionType.PLAY_MONOPOLY:
        return f"MONOPOLY:{RESOURCE[value]}"
    if action_type == ActionType.MOVE_ROBBER:
        coordinate, victim = value
        victim_index = -1 if victim is None else colors.index(victim)
        return f"ROBBER:{tiles[coordinate]}:{victim_index}"
    if action_type == ActionType.MARITIME_TRADE:
        give, receive = value[0], value[-1]
        return f"MARITIME:{RESOURCE[give]}:{RESOURCE[receive]}:{len(value) - 1}"
    if action_type == ActionType.END_TURN:
        return "END_TURN"
    raise ValueError(f"unsupported Gym action {action_type}")


def module(map_type: str, player_count: int) -> str:
    colors = COLORS[:player_count]
    keys = [key(action_type, value, map_type, colors) for action_type, value in get_action_array(colors, map_type)]
    body = ",\n    ".join(repr(item) for item in keys).replace("'", '"')
    source = "// @generated by rust/tools/export_gym_catalogue.py; do not hand-edit.\n" + f"pub const KEYS: &[&str] = &[\n    {body}\n];\n"
    return subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        input=source,
        text=True,
        check=True,
        capture_output=True,
    ).stdout


def expected() -> dict[Path, str]:
    return {
        GENERATED / f"gym_{map_type.lower()}_{players}.rs": module(map_type, players)
        for map_type in ("BASE", "TOURNAMENT", "MINI")
        for players in (2, 3, 4)
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = expected()
    mismatches = [path for path, contents in files.items() if not path.exists() or path.read_text(encoding="utf-8") != contents]
    if args.check:
        if mismatches:
            raise SystemExit("Gym catalogue artifacts differ: " + ", ".join(map(str, mismatches)))
        print("Gym catalogue artifacts match")
        return
    for path, contents in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8", newline="\n")
    print("wrote 9 Gym catalogue modules")


if __name__ == "__main__":
    main()
