from typing import Any

class Batch:
    def __new__(self, size: int, players: int = 4, map: str = "BASE", seed: int = 0) -> Batch: ...
    def reset_many(self, indices: list[int], seeds: list[int], config: str | None = None) -> dict[str, Any]: ...
    def observe_many(self, indices: list[int]) -> dict[str, Any]: ...
    def step_many(self, indices: list[int], action_ids: list[int]) -> dict[str, Any]: ...
    def step_gym_many(self, indices: list[int], action_ids: list[int]) -> dict[str, Any]: ...
    def rollout_many(self, indices: list[int], seeds: list[int], turn_limit: int = 1000, action_limit: int = 100000, policy: str = "weighted", threads: int = 1) -> dict[str, Any]: ...
