import React, { useEffect, useState, useCallback } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";
import { API_URL } from "../configuration";

import PropTypes from "prop-types";
import { makeStyles } from "@material-ui/core/styles";
import ZoomableBoard from "./ZoomableBoard";

import "./GameScreen.scss";

const useStyles = makeStyles({
  content: {
    height: "100%",
    position: "relative",
  },
});
function GameScreen(props) {
  const classes = useStyles();

  // const { gameId } = useParams();
  // const [state, setState] = useState(null);
  // const [automation, setAutomation] = useState(false);
  // const [inFlightRequest, setInFlightRequest] = useState(false);

  // useEffect(() => {
  //   (async () => {
  //     const response = await fetch(API_URL + "/games/" + gameId);
  //     const data = await response.json();
  //     setState(data);
  //   })();
  // }, [gameId]);

  // const onClickNext = useCallback(async () => {
  //   setInFlightRequest(true);
  //   const response = await axios.post(`${API_URL}/games/${gameId}/tick`);
  //   setInFlightRequest(false);
  //   setState(response.data);
  // }, [gameId]);

  // const onClickAutomation = () => {
  //   setAutomation(!automation);
  // };

  // useEffect(() => {
  //   const interval = setInterval(async () => {
  //     if (automation && !inFlightRequest) {
  //       await onClickNext();
  //     }
  //   }, 50);
  //   return () => clearInterval(interval);
  // }, [automation, inFlightRequest, onClickNext]);
  const state = {
    tiles: [
      {
        coordinate: [0, 0, 0],
        tile: { id: 0, type: "RESOURCE_TILE", resource: "SHEEP", number: 11 },
      },
      {
        coordinate: [1, -1, 0],
        tile: { id: 1, type: "RESOURCE_TILE", resource: "BRICK", number: 4 },
      },
      {
        coordinate: [0, -1, 1],
        tile: { id: 2, type: "RESOURCE_TILE", resource: "BRICK", number: 6 },
      },
      {
        coordinate: [-1, 0, 1],
        tile: { id: 3, type: "RESOURCE_TILE", resource: "WHEAT", number: 3 },
      },
      {
        coordinate: [-1, 1, 0],
        tile: { id: 4, type: "RESOURCE_TILE", resource: "WHEAT", number: 10 },
      },
      {
        coordinate: [0, 1, -1],
        tile: { id: 5, type: "RESOURCE_TILE", resource: "WOOD", number: 5 },
      },
      {
        coordinate: [1, 0, -1],
        tile: { id: 6, type: "RESOURCE_TILE", resource: "WHEAT", number: 6 },
      },
      {
        coordinate: [2, -2, 0],
        tile: { id: 7, type: "RESOURCE_TILE", resource: "WHEAT", number: 9 },
      },
      {
        coordinate: [1, -2, 1],
        tile: { id: 8, type: "RESOURCE_TILE", resource: "ORE", number: 5 },
      },
      {
        coordinate: [0, -2, 2],
        tile: { id: 9, type: "RESOURCE_TILE", resource: "SHEEP", number: 3 },
      },
      {
        coordinate: [-1, -1, 2],
        tile: { id: 10, type: "RESOURCE_TILE", resource: "WOOD", number: 9 },
      },
      {
        coordinate: [-2, 0, 2],
        tile: { id: 11, type: "RESOURCE_TILE", resource: "WOOD", number: 11 },
      },
      {
        coordinate: [-2, 1, 1],
        tile: { id: 12, type: "RESOURCE_TILE", resource: "ORE", number: 8 },
      },
      {
        coordinate: [-2, 2, 0],
        tile: { id: 13, type: "RESOURCE_TILE", resource: "SHEEP", number: 4 },
      },
      {
        coordinate: [-1, 2, -1],
        tile: { id: 14, type: "RESOURCE_TILE", resource: "BRICK", number: 12 },
      },
      {
        coordinate: [0, 2, -2],
        tile: { id: 15, type: "RESOURCE_TILE", resource: "SHEEP", number: 2 },
      },
      { coordinate: [1, 1, -2], tile: { id: 16, type: "DESERT" } },
      {
        coordinate: [2, 0, -2],
        tile: { id: 17, type: "RESOURCE_TILE", resource: "WOOD", number: 8 },
      },
      {
        coordinate: [2, -1, -1],
        tile: { id: 18, type: "RESOURCE_TILE", resource: "ORE", number: 10 },
      },
      {
        coordinate: [3, -3, 0],
        tile: { id: 0, type: "PORT", direction: "WEST", resource: "ORE" },
      },
      { coordinate: [2, -3, 1], tile: { type: "WATER" } },
      {
        coordinate: [1, -3, 2],
        tile: { id: 1, type: "PORT", direction: "NORTHWEST", resource: null },
      },
      { coordinate: [0, -3, 3], tile: { type: "WATER" } },
      {
        coordinate: [-1, -2, 3],
        tile: { id: 2, type: "PORT", direction: "NORTHWEST", resource: "WOOD" },
      },
      { coordinate: [-2, -1, 3], tile: { type: "WATER" } },
      {
        coordinate: [-3, 0, 3],
        tile: { id: 3, type: "PORT", direction: "NORTHEAST", resource: null },
      },
      { coordinate: [-3, 1, 2], tile: { type: "WATER" } },
      {
        coordinate: [-3, 2, 1],
        tile: { id: 4, type: "PORT", direction: "EAST", resource: "SHEEP" },
      },
      { coordinate: [-3, 3, 0], tile: { type: "WATER" } },
      {
        coordinate: [-2, 3, -1],
        tile: { id: 5, type: "PORT", direction: "EAST", resource: "WHEAT" },
      },
      { coordinate: [-1, 3, -2], tile: { type: "WATER" } },
      {
        coordinate: [0, 3, -3],
        tile: { id: 6, type: "PORT", direction: "SOUTHEAST", resource: null },
      },
      { coordinate: [1, 2, -3], tile: { type: "WATER" } },
      {
        coordinate: [2, 1, -3],
        tile: { id: 7, type: "PORT", direction: "SOUTHWEST", resource: null },
      },
      { coordinate: [3, 0, -3], tile: { type: "WATER" } },
      {
        coordinate: [3, -1, -2],
        tile: {
          id: 8,
          type: "PORT",
          direction: "SOUTHWEST",
          resource: "BRICK",
        },
      },
      { coordinate: [3, -2, -1], tile: { type: "WATER" } },
    ],
    nodes: {
      0: {
        id: 0,
        tile_coordinate: [1, 0, -1],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      1: {
        id: 1,
        tile_coordinate: [1, 0, -1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      2: {
        id: 2,
        tile_coordinate: [0, -1, 1],
        direction: "NORTH",
        building: null,
        color: null,
      },
      3: {
        id: 3,
        tile_coordinate: [-1, 0, 1],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      4: {
        id: 4,
        tile_coordinate: [-1, 1, 0],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      5: {
        id: 5,
        tile_coordinate: [0, 1, -1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      6: {
        id: 6,
        tile_coordinate: [2, -1, -1],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      7: {
        id: 7,
        tile_coordinate: [2, -1, -1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      8: {
        id: 8,
        tile_coordinate: [1, -2, 1],
        direction: "NORTH",
        building: null,
        color: null,
      },
      9: {
        id: 9,
        tile_coordinate: [1, -2, 1],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      10: {
        id: 10,
        tile_coordinate: [0, -2, 2],
        direction: "NORTH",
        building: null,
        color: null,
      },
      11: {
        id: 11,
        tile_coordinate: [-1, -1, 2],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      12: {
        id: 12,
        tile_coordinate: [-1, -1, 2],
        direction: "NORTH",
        building: null,
        color: null,
      },
      13: {
        id: 13,
        tile_coordinate: [-2, 0, 2],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      14: {
        id: 14,
        tile_coordinate: [-2, 1, 1],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      15: {
        id: 15,
        tile_coordinate: [-2, 1, 1],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      16: {
        id: 16,
        tile_coordinate: [-1, 2, -1],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      17: {
        id: 17,
        tile_coordinate: [-2, 2, 0],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      18: {
        id: 18,
        tile_coordinate: [-1, 2, -1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      19: {
        id: 19,
        tile_coordinate: [1, 1, -2],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      20: {
        id: 20,
        tile_coordinate: [1, 1, -2],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      21: {
        id: 21,
        tile_coordinate: [0, 2, -2],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      22: {
        id: 22,
        tile_coordinate: [2, 0, -2],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      23: {
        id: 23,
        tile_coordinate: [2, -1, -1],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      24: {
        id: 24,
        tile_coordinate: [3, -2, -1],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      25: {
        id: 25,
        tile_coordinate: [3, -2, -1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      26: {
        id: 26,
        tile_coordinate: [2, -3, 1],
        direction: "NORTH",
        building: null,
        color: null,
      },
      27: {
        id: 27,
        tile_coordinate: [2, -3, 1],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      28: {
        id: 28,
        tile_coordinate: [1, -3, 2],
        direction: "NORTH",
        building: null,
        color: null,
      },
      29: {
        id: 29,
        tile_coordinate: [1, -3, 2],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      30: {
        id: 30,
        tile_coordinate: [0, -3, 3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      31: {
        id: 31,
        tile_coordinate: [-1, -2, 3],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      32: {
        id: 32,
        tile_coordinate: [-1, -2, 3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      33: {
        id: 33,
        tile_coordinate: [-2, -1, 3],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      34: {
        id: 34,
        tile_coordinate: [-2, -1, 3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      35: {
        id: 35,
        tile_coordinate: [-3, 0, 3],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      36: {
        id: 36,
        tile_coordinate: [-3, 1, 2],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      37: {
        id: 37,
        tile_coordinate: [-3, 1, 2],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      38: {
        id: 38,
        tile_coordinate: [-3, 2, 1],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      39: {
        id: 39,
        tile_coordinate: [-3, 2, 1],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      40: {
        id: 40,
        tile_coordinate: [-2, 3, -1],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      41: {
        id: 41,
        tile_coordinate: [-3, 3, 0],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      42: {
        id: 42,
        tile_coordinate: [-2, 3, -1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      43: {
        id: 43,
        tile_coordinate: [-1, 3, -2],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      44: {
        id: 44,
        tile_coordinate: [-1, 3, -2],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      45: {
        id: 45,
        tile_coordinate: [1, 2, -3],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      46: {
        id: 46,
        tile_coordinate: [1, 2, -3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      47: {
        id: 47,
        tile_coordinate: [0, 3, -3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      48: {
        id: 48,
        tile_coordinate: [2, 1, -3],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      49: {
        id: 49,
        tile_coordinate: [2, 1, -3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      50: {
        id: 50,
        tile_coordinate: [3, 0, -3],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      51: {
        id: 51,
        tile_coordinate: [3, -1, -2],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      52: {
        id: 52,
        tile_coordinate: [3, -1, -2],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      53: {
        id: 53,
        tile_coordinate: [3, -2, -1],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      54: {
        id: 54,
        tile_coordinate: [3, -2, -1],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      55: {
        id: 55,
        tile_coordinate: [3, -3, 0],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      56: {
        id: 56,
        tile_coordinate: [3, -3, 0],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      57: {
        id: 57,
        tile_coordinate: [2, -3, 1],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      58: {
        id: 58,
        tile_coordinate: [2, -3, 1],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      59: {
        id: 59,
        tile_coordinate: [1, -3, 2],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      60: {
        id: 60,
        tile_coordinate: [1, -3, 2],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      61: {
        id: 61,
        tile_coordinate: [0, -3, 3],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      62: {
        id: 62,
        tile_coordinate: [0, -3, 3],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      63: {
        id: 63,
        tile_coordinate: [0, -3, 3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      64: {
        id: 64,
        tile_coordinate: [-1, -2, 3],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      65: {
        id: 65,
        tile_coordinate: [-1, -2, 3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      66: {
        id: 66,
        tile_coordinate: [-2, -1, 3],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      67: {
        id: 67,
        tile_coordinate: [-2, -1, 3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      68: {
        id: 68,
        tile_coordinate: [-3, 0, 3],
        direction: "SOUTHEAST",
        building: null,
        color: null,
      },
      69: {
        id: 69,
        tile_coordinate: [-3, 0, 3],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      70: {
        id: 70,
        tile_coordinate: [-3, 0, 3],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      71: {
        id: 71,
        tile_coordinate: [-3, 1, 2],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      72: {
        id: 72,
        tile_coordinate: [-3, 1, 2],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      73: {
        id: 73,
        tile_coordinate: [-3, 2, 1],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      74: {
        id: 74,
        tile_coordinate: [-3, 2, 1],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      75: {
        id: 75,
        tile_coordinate: [-3, 3, 0],
        direction: "SOUTH",
        building: null,
        color: null,
      },
      76: {
        id: 76,
        tile_coordinate: [-2, 3, -1],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      77: {
        id: 77,
        tile_coordinate: [-3, 3, 0],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      78: {
        id: 78,
        tile_coordinate: [-3, 3, 0],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      79: {
        id: 79,
        tile_coordinate: [-1, 3, -2],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      80: {
        id: 80,
        tile_coordinate: [-2, 3, -1],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      81: {
        id: 81,
        tile_coordinate: [0, 3, -3],
        direction: "SOUTHWEST",
        building: null,
        color: null,
      },
      82: {
        id: 82,
        tile_coordinate: [-1, 3, -2],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      83: {
        id: 83,
        tile_coordinate: [0, 3, -3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      84: {
        id: 84,
        tile_coordinate: [1, 2, -3],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      85: {
        id: 85,
        tile_coordinate: [0, 3, -3],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      86: {
        id: 86,
        tile_coordinate: [1, 2, -3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      87: {
        id: 87,
        tile_coordinate: [2, 1, -3],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      88: {
        id: 88,
        tile_coordinate: [2, 1, -3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      89: {
        id: 89,
        tile_coordinate: [3, 0, -3],
        direction: "NORTHWEST",
        building: null,
        color: null,
      },
      90: {
        id: 90,
        tile_coordinate: [3, 0, -3],
        direction: "NORTH",
        building: null,
        color: null,
      },
      91: {
        id: 91,
        tile_coordinate: [3, 0, -3],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      92: {
        id: 92,
        tile_coordinate: [3, -1, -2],
        direction: "NORTH",
        building: null,
        color: null,
      },
      93: {
        id: 93,
        tile_coordinate: [3, -1, -2],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
      94: {
        id: 94,
        tile_coordinate: [3, -2, -1],
        direction: "NORTH",
        building: null,
        color: null,
      },
      95: {
        id: 95,
        tile_coordinate: [3, -2, -1],
        direction: "NORTHEAST",
        building: null,
        color: null,
      },
    },
    edges: [
      {
        id: [1, 2],
        tile_coordinate: [1, -1, 0],
        direction: "WEST",
        color: null,
      },
      {
        id: [2, 3],
        tile_coordinate: [0, -1, 1],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [3, 4],
        tile_coordinate: [-1, 0, 1],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [4, 5],
        tile_coordinate: [-1, 1, 0],
        direction: "EAST",
        color: null,
      },
      {
        id: [5, 0],
        tile_coordinate: [0, 1, -1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [0, 1],
        tile_coordinate: [1, 0, -1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [7, 8],
        tile_coordinate: [2, -2, 0],
        direction: "WEST",
        color: null,
      },
      {
        id: [8, 9],
        tile_coordinate: [1, -2, 1],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [9, 2],
        tile_coordinate: [0, -1, 1],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [1, 6],
        tile_coordinate: [1, 0, -1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [6, 7],
        tile_coordinate: [2, -1, -1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [9, 10],
        tile_coordinate: [1, -2, 1],
        direction: "WEST",
        color: null,
      },
      {
        id: [10, 11],
        tile_coordinate: [0, -2, 2],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [11, 12],
        tile_coordinate: [-1, -1, 2],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [12, 3],
        tile_coordinate: [-1, 0, 1],
        direction: "EAST",
        color: null,
      },
      {
        id: [12, 13],
        tile_coordinate: [-1, -1, 2],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [13, 14],
        tile_coordinate: [-2, 0, 2],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [14, 15],
        tile_coordinate: [-2, 1, 1],
        direction: "EAST",
        color: null,
      },
      {
        id: [15, 4],
        tile_coordinate: [-1, 1, 0],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [15, 17],
        tile_coordinate: [-2, 1, 1],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [17, 18],
        tile_coordinate: [-2, 2, 0],
        direction: "EAST",
        color: null,
      },
      {
        id: [18, 16],
        tile_coordinate: [-1, 2, -1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [16, 5],
        tile_coordinate: [0, 1, -1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [20, 0],
        tile_coordinate: [1, 0, -1],
        direction: "WEST",
        color: null,
      },
      {
        id: [16, 21],
        tile_coordinate: [-1, 2, -1],
        direction: "EAST",
        color: null,
      },
      {
        id: [21, 19],
        tile_coordinate: [0, 2, -2],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [19, 20],
        tile_coordinate: [1, 1, -2],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [23, 6],
        tile_coordinate: [2, -1, -1],
        direction: "WEST",
        color: null,
      },
      {
        id: [20, 22],
        tile_coordinate: [1, 1, -2],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [22, 23],
        tile_coordinate: [2, 0, -2],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [25, 26],
        tile_coordinate: [3, -3, 0],
        direction: "WEST",
        color: null,
      },
      {
        id: [26, 27],
        tile_coordinate: [2, -3, 1],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [27, 8],
        tile_coordinate: [1, -2, 1],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [7, 24],
        tile_coordinate: [2, -1, -1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [24, 25],
        tile_coordinate: [3, -2, -1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [27, 28],
        tile_coordinate: [2, -3, 1],
        direction: "WEST",
        color: null,
      },
      {
        id: [28, 29],
        tile_coordinate: [1, -3, 2],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [29, 10],
        tile_coordinate: [0, -2, 2],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [29, 30],
        tile_coordinate: [1, -3, 2],
        direction: "WEST",
        color: null,
      },
      {
        id: [30, 31],
        tile_coordinate: [0, -3, 3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [31, 32],
        tile_coordinate: [-1, -2, 3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [32, 11],
        tile_coordinate: [-1, -1, 2],
        direction: "EAST",
        color: null,
      },
      {
        id: [32, 33],
        tile_coordinate: [-1, -2, 3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [33, 34],
        tile_coordinate: [-2, -1, 3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [34, 13],
        tile_coordinate: [-2, 0, 2],
        direction: "EAST",
        color: null,
      },
      {
        id: [34, 35],
        tile_coordinate: [-2, -1, 3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [35, 36],
        tile_coordinate: [-3, 0, 3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [36, 37],
        tile_coordinate: [-3, 1, 2],
        direction: "EAST",
        color: null,
      },
      {
        id: [37, 14],
        tile_coordinate: [-2, 1, 1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [37, 38],
        tile_coordinate: [-3, 1, 2],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [38, 39],
        tile_coordinate: [-3, 2, 1],
        direction: "EAST",
        color: null,
      },
      {
        id: [39, 17],
        tile_coordinate: [-2, 2, 0],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [39, 41],
        tile_coordinate: [-3, 2, 1],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [41, 42],
        tile_coordinate: [-3, 3, 0],
        direction: "EAST",
        color: null,
      },
      {
        id: [42, 40],
        tile_coordinate: [-2, 3, -1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [40, 18],
        tile_coordinate: [-1, 2, -1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [40, 44],
        tile_coordinate: [-2, 3, -1],
        direction: "EAST",
        color: null,
      },
      {
        id: [44, 43],
        tile_coordinate: [-1, 3, -2],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [43, 21],
        tile_coordinate: [0, 2, -2],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [46, 19],
        tile_coordinate: [1, 1, -2],
        direction: "WEST",
        color: null,
      },
      {
        id: [43, 47],
        tile_coordinate: [-1, 3, -2],
        direction: "EAST",
        color: null,
      },
      {
        id: [47, 45],
        tile_coordinate: [0, 3, -3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [45, 46],
        tile_coordinate: [1, 2, -3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [49, 22],
        tile_coordinate: [2, 0, -2],
        direction: "WEST",
        color: null,
      },
      {
        id: [46, 48],
        tile_coordinate: [1, 2, -3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [48, 49],
        tile_coordinate: [2, 1, -3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [51, 52],
        tile_coordinate: [3, -1, -2],
        direction: "WEST",
        color: null,
      },
      {
        id: [52, 23],
        tile_coordinate: [2, -1, -1],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [49, 50],
        tile_coordinate: [2, 1, -3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [50, 51],
        tile_coordinate: [3, 0, -3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [53, 24],
        tile_coordinate: [3, -2, -1],
        direction: "WEST",
        color: null,
      },
      {
        id: [52, 53],
        tile_coordinate: [3, -1, -2],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [55, 56],
        tile_coordinate: [3, -3, 0],
        direction: "EAST",
        color: null,
      },
      {
        id: [56, 57],
        tile_coordinate: [3, -3, 0],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [57, 26],
        tile_coordinate: [2, -3, 1],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [25, 54],
        tile_coordinate: [3, -2, -1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [54, 55],
        tile_coordinate: [3, -3, 0],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [57, 58],
        tile_coordinate: [2, -3, 1],
        direction: "EAST",
        color: null,
      },
      {
        id: [58, 59],
        tile_coordinate: [2, -3, 1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [59, 28],
        tile_coordinate: [1, -3, 2],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [59, 60],
        tile_coordinate: [1, -3, 2],
        direction: "EAST",
        color: null,
      },
      {
        id: [60, 61],
        tile_coordinate: [1, -3, 2],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [61, 30],
        tile_coordinate: [0, -3, 3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [61, 62],
        tile_coordinate: [0, -3, 3],
        direction: "EAST",
        color: null,
      },
      {
        id: [62, 63],
        tile_coordinate: [0, -3, 3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [63, 64],
        tile_coordinate: [0, -3, 3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [64, 31],
        tile_coordinate: [-1, -2, 3],
        direction: "EAST",
        color: null,
      },
      {
        id: [64, 65],
        tile_coordinate: [-1, -2, 3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [65, 66],
        tile_coordinate: [-1, -2, 3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [66, 33],
        tile_coordinate: [-2, -1, 3],
        direction: "EAST",
        color: null,
      },
      {
        id: [66, 67],
        tile_coordinate: [-2, -1, 3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [67, 68],
        tile_coordinate: [-2, -1, 3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [68, 35],
        tile_coordinate: [-3, 0, 3],
        direction: "EAST",
        color: null,
      },
      {
        id: [68, 69],
        tile_coordinate: [-3, 0, 3],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [69, 70],
        tile_coordinate: [-3, 0, 3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [70, 71],
        tile_coordinate: [-3, 0, 3],
        direction: "WEST",
        color: null,
      },
      {
        id: [71, 36],
        tile_coordinate: [-3, 1, 2],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [71, 72],
        tile_coordinate: [-3, 1, 2],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [72, 73],
        tile_coordinate: [-3, 1, 2],
        direction: "WEST",
        color: null,
      },
      {
        id: [73, 38],
        tile_coordinate: [-3, 2, 1],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [73, 74],
        tile_coordinate: [-3, 2, 1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [74, 75],
        tile_coordinate: [-3, 2, 1],
        direction: "WEST",
        color: null,
      },
      {
        id: [75, 41],
        tile_coordinate: [-3, 3, 0],
        direction: "SOUTHEAST",
        color: null,
      },
      {
        id: [75, 77],
        tile_coordinate: [-3, 3, 0],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [77, 78],
        tile_coordinate: [-3, 3, 0],
        direction: "WEST",
        color: null,
      },
      {
        id: [78, 76],
        tile_coordinate: [-3, 3, 0],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [76, 42],
        tile_coordinate: [-2, 3, -1],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [76, 80],
        tile_coordinate: [-2, 3, -1],
        direction: "WEST",
        color: null,
      },
      {
        id: [80, 79],
        tile_coordinate: [-2, 3, -1],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [79, 44],
        tile_coordinate: [-1, 3, -2],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [79, 82],
        tile_coordinate: [-1, 3, -2],
        direction: "WEST",
        color: null,
      },
      {
        id: [82, 81],
        tile_coordinate: [-1, 3, -2],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [81, 47],
        tile_coordinate: [0, 3, -3],
        direction: "SOUTHWEST",
        color: null,
      },
      {
        id: [84, 45],
        tile_coordinate: [1, 2, -3],
        direction: "WEST",
        color: null,
      },
      {
        id: [81, 85],
        tile_coordinate: [0, 3, -3],
        direction: "WEST",
        color: null,
      },
      {
        id: [85, 83],
        tile_coordinate: [0, 3, -3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [83, 84],
        tile_coordinate: [0, 3, -3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [87, 48],
        tile_coordinate: [2, 1, -3],
        direction: "WEST",
        color: null,
      },
      {
        id: [84, 86],
        tile_coordinate: [1, 2, -3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [86, 87],
        tile_coordinate: [1, 2, -3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [89, 50],
        tile_coordinate: [3, 0, -3],
        direction: "WEST",
        color: null,
      },
      {
        id: [87, 88],
        tile_coordinate: [2, 1, -3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [88, 89],
        tile_coordinate: [2, 1, -3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [91, 92],
        tile_coordinate: [3, 0, -3],
        direction: "EAST",
        color: null,
      },
      {
        id: [92, 51],
        tile_coordinate: [3, -1, -2],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [89, 90],
        tile_coordinate: [3, 0, -3],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [90, 91],
        tile_coordinate: [3, 0, -3],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [93, 94],
        tile_coordinate: [3, -1, -2],
        direction: "EAST",
        color: null,
      },
      {
        id: [94, 53],
        tile_coordinate: [3, -2, -1],
        direction: "NORTHWEST",
        color: null,
      },
      {
        id: [92, 93],
        tile_coordinate: [3, -1, -2],
        direction: "NORTHEAST",
        color: null,
      },
      {
        id: [95, 54],
        tile_coordinate: [3, -2, -1],
        direction: "EAST",
        color: null,
      },
      {
        id: [94, 95],
        tile_coordinate: [3, -2, -1],
        direction: "NORTHEAST",
        color: null,
      },
    ],
    actions: [],
    players: [
      {
        name: "BAR",
        color: "BLUE",
        public_victory_points: 0,
        actual_victory_points: 0,
        resource_deck: { WOOD: 0, BRICK: 0, SHEEP: 0, WHEAT: 0, ORE: 0 },
        development_deck: {
          KNIGHT: 0,
          YEAR_OF_PLENTY: 0,
          MONOPOLY: 0,
          ROAD_BUILDING: 0,
          VICTORY_POINT: 0,
        },
        played_development_cards: {
          KNIGHT: 0,
          YEAR_OF_PLENTY: 0,
          MONOPOLY: 0,
          ROAD_BUILDING: 0,
          VICTORY_POINT: 0,
        },
        has_road: false,
        has_army: false,
        roads_available: 15,
        settlements_available: 5,
        cities_available: 4,
        has_rolled: false,
        playable_development_cards: [],
      },
      {
        name: "FOO",
        color: "RED",
        public_victory_points: 0,
        actual_victory_points: 0,
        resource_deck: { WOOD: 0, BRICK: 0, SHEEP: 0, WHEAT: 0, ORE: 0 },
        development_deck: {
          KNIGHT: 0,
          YEAR_OF_PLENTY: 0,
          MONOPOLY: 0,
          ROAD_BUILDING: 0,
          VICTORY_POINT: 0,
        },
        played_development_cards: {
          KNIGHT: 0,
          YEAR_OF_PLENTY: 0,
          MONOPOLY: 0,
          ROAD_BUILDING: 0,
          VICTORY_POINT: 0,
        },
        has_road: false,
        has_army: false,
        roads_available: 15,
        settlements_available: 5,
        cities_available: 4,
        has_rolled: false,
        playable_development_cards: [],
        model_path: "experimental/models/1v1-rep-a",
      },
    ],
    robber_coordinate: [1, 1, -2],
  };

  console.log(state);

  return (
    <main className={classes.content}>
      {state !== null && <ZoomableBoard state={state} />}
    </main>
  );
}

GameScreen.propTypes = {
  /**
   * Injected by the documentation to work in an iframe.
   * You won't need it on your project.
   */
  window: PropTypes.func,
};

export default GameScreen;
